// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for biztalkserver metrics.
type MetricsConfig struct {
	BiztalkHostInstancesStatus     MetricConfig `mapstructure:"biztalk.host_instances_status"`
	BiztalkOrchestrationsStatus    MetricConfig `mapstructure:"biztalk.orchestrations_status"`
	BiztalkReceiveLocationsEnabled MetricConfig `mapstructure:"biztalk.receive_locations_enabled"`
	BiztalkSendPortsStatus         MetricConfig `mapstructure:"biztalk.send_ports_status"`
	BiztalkSendportGroupsStatus    MetricConfig `mapstructure:"biztalk.sendport_groups_status"`
	BiztalkSuspendedInstances      MetricConfig `mapstructure:"biztalk.suspended_instances"`
	BiztalkSuspendedMessages       MetricConfig `mapstructure:"biztalk.suspended_messages"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		BiztalkHostInstancesStatus: MetricConfig{
			Enabled: true,
		},
		BiztalkOrchestrationsStatus: MetricConfig{
			Enabled: true,
		},
		BiztalkReceiveLocationsEnabled: MetricConfig{
			Enabled: true,
		},
		BiztalkSendPortsStatus: MetricConfig{
			Enabled: true,
		},
		BiztalkSendportGroupsStatus: MetricConfig{
			Enabled: true,
		},
		BiztalkSuspendedInstances: MetricConfig{
			Enabled: true,
		},
		BiztalkSuspendedMessages: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for biztalkserver resource attributes.
type ResourceAttributesConfig struct {
	BiztalkName ResourceAttributeConfig `mapstructure:"biztalk.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		BiztalkName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for biztalkserver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
